# podman kube play --replace --publish 8080:3000 cento-demo-pod.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: cento-demo
spec:
  hostIPC: true
  restartPolicy: Never

  containers:
    - name: redis
      image: docker.io/library/redis

    - name: ntopng
      image: ntopng:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - mountPath: /opt/ntop/ntopng/config
          name: ntopng-config
        - mountPath: /etc/ntopng.license
          name: ntopng-license

    - name: cento
      image: cento:latest

      args:
        - "--threads"
        - "2"
        - "--flow-offload"

      securityContext:
        privileged: true

      volumeMounts:
        - mountPath: /dev/nt3gd
          name: dev-nt3gd
        - mountPath: /var/run/napatech
          name: napatech-run
        - mountPath: /opt/napatech3/lib
          name: napatech-lib
        - mountPath: /opt/napatech3/bin
          name: napatech-bin
        - mountPath: /opt/ntop/cento/config
          name: cento-config
        # Licenses
        - mountPath: /etc/pf_ring/000-0000-00-00-0000-000000
          name: pfring-license
        - mountPath: /etc/cento.license
          name: cento-license

  volumes:
    - name: dev-nt3gd
      hostPath:
        path: /dev/nt3gd
        type: CharDevice         
    - name: napatech-run
      hostPath:
        path: /var/run/napatech
        type: Directory
    - name: napatech-lib
      hostPath:
        path: /opt/napatech3/lib
        type: Directory
    - name: napatech-bin
      hostPath:
        path: /opt/napatech3/bin
        type: Directory
    # Configs
    - name: cento-config
      hostPath:
        path: /opt/ntop/cento/config
        type: Directory
    - name: ntopng-config
      hostPath:
        path: /opt/ntop/ntopng/config
        type: Directory
    # Licenses
    - name: pfring-license
      hostPath:
        path: /opt/ntop/licenses/pfring.license
        type: File
    - name: cento-license
      hostPath:
        path: /opt/ntop/licenses/cento.license
        type: File
    - name: ntopng-license
      hostPath:
        path: /opt/ntop/licenses/ntopng.license
        type: File
